### ISSUE TITLE
Implement proper diagonal lines to child branches which adjust angle appropriately.

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#14]

**Comment by kylemas** [comment]
Lines render using 'react-lineto' module. Connects two nodes using their class name, which is assigned to the node div. 
<img width="417" alt="Screen Shot 2019-08-06 at 1 55 08 PM" src="https://user-images.githubusercontent.com/34122775/62576613-11faf800-b852-11e9-9639-0f592da9c7b1.png">
<img width="426" alt="Screen Shot 2019-08-06 at 1 55 50 PM" src="https://user-images.githubusercontent.com/34122775/62576614-11faf800-b852-11e9-8ef4-5cb253293c60.png">
<img width="398" alt="Screen Shot 2019-08-06 at 1 56 05 PM" src="https://user-images.githubusercontent.com/34122775/62576615-12938e80-b852-11e9-83e4-02d9a3e89a51.png">
