### ISSUE TITLE
Logic Symbols in Nodes

### ISSUE THREAD

**Issue by drgilbert** [McTano/Rudolf#16]
It would be great (though non-essential, and more of a superficial issue) to display the actual logic symbols in the nodes rather than the text equivalents. While the user would still enter a conditional by typing, for example, "=>", this would then be rendered as the proper conditional symbol. 

Thinking ahead, it might be very nice (though I don't know exactly how feasible this is), to then allow different norms for the logic symbols to be supported. So the user would always enter "=>", but if you are using my book, this would be displayed in the tree as the arrow, but if you are using Jonathan's, for example, it displays as the horseshoe. This would mirror what is already supported in the various forallx editions and increase the ability for instructors to use the tree functionality without having to change their preferred approach.

**Comment by kylemas** [comment]
#25
