### ISSUE TITLE
Space out formulas vertically so that each row lines up.

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#39]
When a user appends new nodes to the bottom of all open branches in part of the tree, some branches may be shorter than others.
The new nodes should be spaced consistently so that uneven branches can line up when they receive new nodes which start on the same row.

**Comment by McTano** [comment]
Example:
![uneven_rows](https://user-images.githubusercontent.com/17462266/84543528-6069f600-acb0-11ea-8541-9010b254c5cb.png)

The formulas on row 6 should appear at the same height vertically.
As you can see, there is some logic which attempts to get this right and draws a bit of extra line on the left, but it doesn't quite work.

**Comment by orbit-stabilizer** [comment]
I get something different when I run that example. Is what I have the expected behaviour?  
<img width="561" alt="image" src="https://user-images.githubusercontent.com/33772483/85228964-b4a16400-b39b-11ea-8270-82391a34d84c.png">

**Comment by McTano** [comment]
It looks like you added the resolution for P&Q to each branch separately. On the left you've got 6,7 and on the right I think the checker would accept that as correct, but I'm not sure.
To reproduce the behaviour above you need to right-click a formula above where they branch (e.g. row 2) and select "continue branch with 2 nodes". Then you'll get row 6,7 on both sides.
