### ISSUE TITLE
Add a pre-commit hook to run prettier

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#40]
EDIT:
Limit this to just a prettier hook for now, and leave the type-checking and linting for a pipeline which runs after push.

ORIGINAL:
We should set up git hooks to run `prettier`, `eslint --fix`, and `tsc` on our repo each time we commit code.
tsc errors or unfixable eslint errors should prevent the commit unless the checks are manually skipped.

**Comment by lf-** [comment]
Git client side hooks like these would need to be installed by some script in our repository as they reside in `.git` and do not come down with clones. Should we make a task with package.json that does this installation?

Also, if we are using client side hooks for this, we should potentially use CI (when we implement CI) to enforce that the code is compliant with the standards as it is not necessarily the case that everyone chooses to install the hooks.

**Comment by McTano** [comment]
We can use husky to make it part of the npm install process.
That's the only way I've used them so I didn't really know about the
limitations of doing it manually.
The prettier docs have instructions for how to do it a couple of different
ways.
The husky + prettier-quick method seems good.

**Comment by lf-** [comment]
Ah, ok. I haven't maintained this kind of thing in a JavaScript project before, only used it for circuit boards, so wasn't sure as to the tooling. Makes sense!
