### ISSUE TITLE
Fix delay between selection and change in tree

### ISSUE THREAD

**Issue by orbit-stabilizer** [McTano/Rudolf#46]
I have noticed that when I change the selection, it will not update the tree until I click somewhere on the window.

See here for an example: ![change_after_click](https://user-images.githubusercontent.com/33772483/82604242-dc1ccb00-9b68-11ea-95eb-c87052328568.gif)

**Comment by McTano** [comment]
Thanks for the bug report.
I'll look into it.

**Comment by orbit-stabilizer** [comment]
There were a couple things I found. 

In the PremisesSelector component, there was both a onChange and an onBlur on the select. They both called handleSelect. So there was a duplication that occurred when changing the selection and trying to use the arrows to go back - I can show a gif if this isn't clear. 

In handleSubmitPremises, because of the asynchronous nature of setPremises, premiseArray had the old version of premises - which caused the same thing to stay on the screen until the next update. The easy way I got around that was by changing
`const premiseArray = premises.split(',')` to  `const premiseArray = rawInput.split(',')`. This seems to have fixed the issue.

Would you like me to submit a PR?

**Comment by McTano** [comment]
Thanks for investigating. Please feel free to submit a PR.
