### ISSUE TITLE
Document the UI

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#48]
It would be good if we had documentation on how to use the widget.

As a first stage maybe just an explanation of the controls, and the difference between "nodes" and "formulas/rows". 

It would be nice if the user didn't have to think about that distinction, but at the moment we're stuck with it, so it would be good to describe it.

In the future, we could also add an explanation of how to type the various logic symbols, although maybe that should live at the FiraLogic repo.

**Comment by orbit-stabilizer** [comment]
As someone new to the project and someone who doesn't really know the difference between nodes or formulas/rows, I could review the documentation and see how helpful it is.

**Comment by kylemas** [comment]
Definitely! 

@McTano I can work on this as well.

**Comment by McTano** [comment]
Yeah. It's undocumented except for instant message conversations, at this
point.

**Comment by orbit-stabilizer** [comment]
I took a look at the Wiki and it's super readable to me - especially with the images!

**Comment by McTano** [comment]
Great, I'll close this.
