### ISSUE TITLE
Make trees geometrically well-behaved.

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#52]
Currently, the trees double in width each time we double the number of branches.

Ideally, we want to keep the trees within a fixed width, but for a start, I'd settle for a linear increase of width.

**Comment by mbecker20** [comment]
have you tried min-width / max-width in css?

**Comment by McTano** [comment]
@mbecker20
I forget what I have and haven't tried. I'd love for you to see what you can do with this.

**Comment by mbecker20** [comment]
Definitely. I'll get on it.

**Comment by mbecker20** [comment]
This is pretty much solved by using the AutosizeInput for the node formulas. We can reopen this again if we feel more is necessary for this issue later on.

**Comment by McTano** [comment]
> 
> 
> This is pretty much solved by using the AutosizeInput for the node formulas. We can reopen this again if we feel more is necessary for this issue later on.

No, it's not. Nothing important has changed since I created this issue or since we last discussed it.

However, I'm realizing now that my original goal, as stated, is impossible so I'll leave this closed. The breadth of the tree will always grow exponentially in the worst case, since we might be doubling the number of branches.

Given the autoresizing behaviour, it would improve things a bit just to remove the placeholder text, and maybe reduce the padding allotted to each node.

Since the title of this ticket is a bit vague and the original description is impossible, I'll create some more issues for specific improvements.
