### ISSUE TITLE
Move justifications to separate column on the right hand side, row numbers to left.

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#55]
Currently, the justifications and rows both display on every node, even though that information is shared by all the nodes which start on the same row.

A better design would be to move the row numbers to the left and the justifications to the right, as they appear in most logic textbooks. Example from forall-x ubc edition.

![example_tree_forallx](https://user-images.githubusercontent.com/17462266/84545609-68c43000-acb4-11ea-93f2-2e44e8bc6e69.png)

**Comment by mbecker20** [comment]
<img width="1392" alt="Screen Shot 2020-07-25 at 10 03 45 PM" src="https://user-images.githubusercontent.com/49575486/88471894-e047ca80-cec2-11ea-992c-3e639afe65c2.png">

Almost there. Just need to clean up some stuff.
