### ISSUE TITLE
Migrate lines drawn between nodes to react-archer to make them prettier

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#65]
The main problem I still have with the line-to component is that the lines for the left and right branches don't link up properly at the bottom of the parent node. Like this:

![lineto_is_ugly](https://user-images.githubusercontent.com/17462266/86694721-bb95bc80-bfc0-11ea-8ea5-7d580e4e1e78.png)

**Comment by McTano** [comment]
@mbecker20
Feel free to use something other than `react-archer` if you prefer. Up to you.

**Comment by mbecker20** [comment]
I think react archer will be good.

**Comment by McTano** [comment]
closed in PR #66
