### ISSUE TITLE
Problem with new arrows

### ISSUE THREAD

**Issue by orbit-stabilizer** [McTano/Rudolf#67]
The new arrows from #65  aren't working as intended with closing branches with contradictions:

![arrows](https://user-images.githubusercontent.com/33772483/87191499-6223db00-c2a9-11ea-8375-29fed4c434d5.gif)

Edit: Same thing with marking branches as finished.

**Comment by mbecker20** [comment]
I'll look into this. I'm pretty sure I know what the problem is.

**Comment by mbecker20** [comment]
closed with PR #68
